# Generated by gallery/generate.py; do not edit.
function pneumaticcraft_gallery:clear
# cross-pressure_tube-center: pressure_tube horizontal cross
setblock 177 99 183 minecraft:stone
setblock 177 100 183 pneumaticcraft:pressure_tube
# cross-pressure_tube-west: pressure_tube horizontal cross
setblock 176 99 183 minecraft:stone
setblock 176 100 183 pneumaticcraft:pressure_tube
# cross-pressure_tube-east: pressure_tube horizontal cross
setblock 178 99 183 minecraft:stone
setblock 178 100 183 pneumaticcraft:pressure_tube
# cross-pressure_tube-north: pressure_tube horizontal cross
setblock 177 99 182 minecraft:stone
setblock 177 100 182 pneumaticcraft:pressure_tube
# cross-pressure_tube-south: pressure_tube horizontal cross
setblock 177 99 184 minecraft:stone
setblock 177 100 184 pneumaticcraft:pressure_tube
# isolated-pressure_tube: pressure_tube isolated
setblock 177 99 190 minecraft:stone
setblock 177 100 190 pneumaticcraft:pressure_tube
# cross-reinforced_pressure_tube-center: reinforced_pressure_tube horizontal cross
setblock 188 99 183 minecraft:stone
setblock 188 100 183 pneumaticcraft:reinforced_pressure_tube
# cross-reinforced_pressure_tube-west: reinforced_pressure_tube horizontal cross
setblock 187 99 183 minecraft:stone
setblock 187 100 183 pneumaticcraft:reinforced_pressure_tube
# cross-reinforced_pressure_tube-east: reinforced_pressure_tube horizontal cross
setblock 189 99 183 minecraft:stone
setblock 189 100 183 pneumaticcraft:reinforced_pressure_tube
# cross-reinforced_pressure_tube-north: reinforced_pressure_tube horizontal cross
setblock 188 99 182 minecraft:stone
setblock 188 100 182 pneumaticcraft:reinforced_pressure_tube
# cross-reinforced_pressure_tube-south: reinforced_pressure_tube horizontal cross
setblock 188 99 184 minecraft:stone
setblock 188 100 184 pneumaticcraft:reinforced_pressure_tube
# isolated-reinforced_pressure_tube: reinforced_pressure_tube isolated
setblock 188 99 190 minecraft:stone
setblock 188 100 190 pneumaticcraft:reinforced_pressure_tube
# cross-advanced_pressure_tube-center: advanced_pressure_tube horizontal cross
setblock 199 99 183 minecraft:stone
setblock 199 100 183 pneumaticcraft:advanced_pressure_tube
# cross-advanced_pressure_tube-west: advanced_pressure_tube horizontal cross
setblock 198 99 183 minecraft:stone
setblock 198 100 183 pneumaticcraft:advanced_pressure_tube
# cross-advanced_pressure_tube-east: advanced_pressure_tube horizontal cross
setblock 200 99 183 minecraft:stone
setblock 200 100 183 pneumaticcraft:advanced_pressure_tube
# cross-advanced_pressure_tube-north: advanced_pressure_tube horizontal cross
setblock 199 99 182 minecraft:stone
setblock 199 100 182 pneumaticcraft:advanced_pressure_tube
# cross-advanced_pressure_tube-south: advanced_pressure_tube horizontal cross
setblock 199 99 184 minecraft:stone
setblock 199 100 184 pneumaticcraft:advanced_pressure_tube
# isolated-advanced_pressure_tube: advanced_pressure_tube isolated
setblock 199 99 190 minecraft:stone
setblock 199 100 190 pneumaticcraft:advanced_pressure_tube
# tank-small_tank: small_tank empty structural control
setblock 175 99 200 minecraft:stone
setblock 175 100 200 pneumaticcraft:small_tank
# tank-medium_tank: medium_tank empty structural control
setblock 179 99 200 minecraft:stone
setblock 179 100 200 pneumaticcraft:medium_tank
# tank-large_tank: large_tank empty structural control
setblock 183 99 200 minecraft:stone
setblock 183 100 200 pneumaticcraft:large_tank
# tank-huge_tank: huge_tank empty structural control
setblock 187 99 200 minecraft:stone
setblock 187 100 200 pneumaticcraft:huge_tank
# heat-pipe-control: heat pipe stock multipart control
setblock 194 99 200 minecraft:stone
setblock 194 100 200 pneumaticcraft:heat_pipe[east=true,west=true]
# stock-control: stone stock rendering control
setblock 202 99 200 minecraft:stone
setblock 202 100 200 minecraft:stone
# vertical-basic: basic tube vertical connection
setblock 176 100 195 pneumaticcraft:pressure_tube
setblock 176 101 195 pneumaticcraft:pressure_tube
setblock 176 102 195 pneumaticcraft:pressure_tube
# vertical-reinforced: reinforced tube vertical connection
setblock 184 100 195 pneumaticcraft:reinforced_pressure_tube
setblock 184 101 195 pneumaticcraft:reinforced_pressure_tube
setblock 184 102 195 pneumaticcraft:reinforced_pressure_tube
# vertical-advanced: advanced tube vertical connection
setblock 192 100 195 pneumaticcraft:advanced_pressure_tube
setblock 192 101 195 pneumaticcraft:advanced_pressure_tube
setblock 192 102 195 pneumaticcraft:advanced_pressure_tube
# mixed-tier-line: every exact tube tier connects
setblock 198 100 195 pneumaticcraft:pressure_tube
setblock 199 100 195 pneumaticcraft:reinforced_pressure_tube
setblock 200 100 195 pneumaticcraft:advanced_pressure_tube
function pneumaticcraft_gallery:verify
